---
exclude: ['README.markdown']
permalink: ':title'
highligher: true
safe: false
title: 'Kotlin By Example'
collections:
  examples:
     output: true
defaults:
  -
    scope:
      path: ""
      type: examples
    values:
      layout: default
